version: '3.8'

services:
  web:
    build: .    
    container_name: chatbot_backend
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  frontend:
    build: .
    command: streamlit run frontend.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - web
    volumes:
      - .:/app
  db:
    image: mysql:8.0
    container_name: chatbot_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
     - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: